version: '3'

services:
  web-nginx:
    image: nginx
    container_name: web-nginx
    volumes:
      - "./docker-web/www:/usr/share/nginx/html:ro"
      - "./docker-web/log:/var/log/nginx"
      - "./docker-web/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "127.0.0.1:80:80"

  web-php:
    image: 'bitnami/php-fpm:latest'
    container_name: web-php
    volumes:
      - "./docker-web/www:/script:ro"
