version: '3'

services:
  web-nginx:
    image: nginx
    container_name: web-nginx
    volumes:
      - "./docker-web/www:/usr/share/nginx/html:ro"
      - "./docker-web/log:/var/log/nginx"
      - "./docker-web/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "127.0.0.1:80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  web-php:
    image: 'bitnami/php-fpm:latest'
    container_name: web-php
    volumes:
      - "./docker-web/www:/script:ro"

  web-mysql:
    image: mysql
    container_name: web-mysql
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - ./docker-web/tmp/mysql-data:/var/lib/mysql
      - ./docker-web/tmp/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}